# Generated by Django 4.0.5 on 2022-06-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_content_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedContent',
        ),
    ]
